# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRunner():
  def setup_method(self):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  # Test name: LOGIN
  def login(self):
    def delay():
      time.sleep(0.5)

    # 1 | open | /login | 
    self.driver.get("https://dev.mentorapm.com/login")
    # 2 | setWindowSize | 1720x1440 | 
    self.driver.set_window_size(1720, 1440)

    # 3 | type | xpath=//input[@name='email'] | dev@smct.com
    self.driver.find_element(By.XPATH, "//input[@name=\'email\']").send_keys("EMAIL HERE")
    delay()
    # 4 | click | xpath=//button[contains(.,'Next ')] | 
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Next \')]").click()
    delay()
    # 5 | type | xpath=//input[@name='password'] | !M4ee9Ma82fM45fff3ab5a3d
    self.driver.find_element(By.XPATH, "//input[@name=\'password\']").send_keys("PASSWORD HERE")
    delay()
    # 6 | click | xpath=//button[contains(.,'Submit ')] | 
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Submit \')]").click()
    delay()


t = TestRunner()
t.setup_method()
t.login()
t.teardown_method()